version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jonhunt-app
    container_name: jonhunt-container
    ports:
      - "8000:8000"   
      - "6001:6001"   
    environment:
      - APP_KEY=${APP_KEY}
      - APP_ENV=production
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/var/www
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: jonhunt-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
